version: "3.9"
services:
  test:
    build: .
    volumes:
      - ./test-reports:/src/test-reports
    command: behave -f html -o test-reports/test-result.html
    environment:
      - EXCHANGE_URL
      - API_KEY
      - PRIVATE_KEY
      - OTP_SEED